name: Reuse Docker Build workflow

on:
  workflow_dispatch

jobs:
  docker:
    uses: GayathriAV1/ReusableWorkflows/.github/workflows/BuildPythonUsingDocker.yml@main
    with:
      image_name: ${{vars.IMAGE_NAME}}
      python_version: ${{vars.PYTHON_VERSION}}
      python_linter: ${{vars.PYTHON_LINTER}}
      python_test_framework: ${{vars.PYTHON_TEST_FRAMEWORK}}
      req_file_path: ${{vars.REQ_FILE_PATH}}
      tag: $GITHUB_RUN_NUMBER
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}
