name: Reuse Docker Build workflow

on:
  workflow_dispatch

jobs:
  docker:
    uses: GayathriAV1/ReusableWorkflows/.github/workflows/BuildPythonUsingDocker.yml@main
    with:
      image_name: my-Python-Docker-app
